# Generated by Django 2.1.4 on 2018-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steel_app', '0002_auto_20181210_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
